### ISSUE TITLE
Game crashes at mission start

### ISSUE THREAD

**Issue by BABACHORI** [CBATeam/CBA_A3#361] opened 2016-06-04 17:28 UTC
Hi! We have on our server mission that are played about 5 hours and more, but we dont have crashes. Sorry, but i cant provide you RPT file from this mission(it was long ago)
Can you please say what mission do you play and we can test them?

**Comment by Killswitch00** [comment] 2016-06-11 08:32
The CBA team itself is not having problems with long-running missions, but there were reports about this a few months ago. After doing some changes to CBA (and A3 having been updated a few times since then) no reports have come in. Thanks for the offer to help and we're glad to hear that you don't have crashes. :+1:

**Comment by SPS6** [comment] 2016-07-08 01:22
This seems to still be an issue.  One of our developers has been submitting rpt's to you and it is still present in your list of known issues on the current release.  Is there any update or further work being done on this.  Our Altis Life mission on Tanoa map results in users crashing after only a short time then they attempt to join.

**Comment by commy2** [comment] 2016-07-08 08:38
Please upload the *full* RPT file. This part about memory addresses doesn't help us,

**Comment by SPS6** [comment] 2016-07-08 11:08
of course, not a problem:

[arma3_2016-07-08_02-11-10.rpt.txt](https://github.com/CBATeam/CBA_A3/files/354067/arma3_2016-07-08_02-11-10.rpt.txt)

**Comment by commy2** [comment] 2016-07-08 16:06
```
 2:13:19 [10742,129.555,0,"XEH: PreInit started. v2.4.1.160606"]
 2:13:19 Error: Mismatched Begin/EndContexts
 2:13:19 Error: Mismatched Begin/EndContexts
 2:13:19 Error: Mismatched Begin/EndContexts
=======================================================
-------------------------------------------------------
 2:13:19 FileServerActObj::MaintainMainThread() - Called from non main thread!
 2:13:19 FileServerActObj::MaintainMainThread() - Called from non main thread!
Exception code: C0000005 ACCESS_VIOLATION at 01848DC3
```

Isn't related to this issue. It crashes at frame 0. Could be bad scripting too. Just because it happens with CBA, doesn't mean that CBA is the cause. It seems to happen during the preInit phase of XEH, and since that code won't be executed without CBA, it's obvious that the game won't crash (but the intended functions won't run either).

**Comment by SPS6** [comment] 2016-07-08 16:13
Thanks for your help with this!, if it happens when only CBA is loaded where should I be looking for issues? Nothing in the mission file is dependant on CBA or XEH so it will not be calling any of those functions or does CBA/XEH patch some of the BI functions?

**Comment by commy2** [comment] 2016-07-08 17:36
>Nothing in the mission file is dependant on CBA or XEH so it will not be calling any of those functions or does CBA/XEH patch some of the BI functions?

Can you upload that mission ?

>I don't suppose that this could be related to #400 could it?

I don't think so

**Comment by SPS6** [comment] 2016-07-08 18:46
Also this did happen in an almost empty very basic mission when it was hosted Online, testing offline was fine, it started happening after a short time after 2 or 3 people had connected and disconnected (within 10 mins).  I'll grab that small mission file quickly.  Everything seems to work fine until you get it in to an online mp mission.

[Tanoa_Fun.Tanoa.pbo.zip](https://github.com/CBATeam/CBA_A3/files/354889/Tanoa_Fun.Tanoa.pbo.zip)

**Comment by SPS6** [comment] 2016-07-08 19:16
I can give details for our dev server also so you can see what happens on that mission.  If I start the server you can join it for about 1 - 10mins before further attempts to join causes the player's client to crash at the end of the map load screen

![image](https://cloud.githubusercontent.com/assets/4487483/16698912/c688688c-4548-11e6-9704-65f121912249.png)

**Comment by commy2** [comment] 2016-07-08 20:30
I don't see what anything about this has to do with CBA. Please reproduce it without any other mods in a empty mission or find out what addon / mission / script exactly is incompatible. We cannot do the debuging of unknown setups. We just don't have the resources to do that. Sorry.
Also, I repeat, dev / sneak peak branches are and cannot be supported by us. BI is updating these branches multiple times a day and who knows what they broke.

**Comment by SPS6** [comment] 2016-07-08 20:54
Wow, I am sorry, I simply provided what you asked "_Can you upload that mission ? Does it happen with a different one?_" ... I provided a mission that just has the VVS script on it and 4 or 5 placed objects, also FYI it's out of dev/sneek peak and now on Release Candidate to test mod/script compatibility and is not subject to daily updates. "_and who knows what they broke_" is exactly why the RC is available, to find out what they broke.  Could you just clarify what was wrong with that barebones mission that I attached?

A blank mission with only CBA on it crashes player's clients when it is loaded as a multiplayer mission on a server.  Remove CBA and no crashes... that is what makes me suspect that it may be CBA.  Sorry to have prompted that angry response from you, I thought that I had been clear in my first post on here about the RC build being used and the fact that this has been happening on the Tanoa map.  I am very grateful for your assistance up to now

**Comment by BABACHORI** [comment] 2016-07-08 21:03
Hey, problem can be in shity mods that you use. Maybe its just uncompatible with CBA. Search the problem in mods that you use. One more, if you say that you use simple mission and it crash, 95% that its problem in your mods.

**Comment by SPS6** [comment] 2016-07-08 21:05
"A blank mission with **only CBA** on it crashes player's clients when it is loaded as a multiplayer mission on a server. Remove CBA and no crashes... that is what makes me suspect that it may be CBA."

I have no shitty mods or any other type of mod loaded when it crashes **ONLY** CBA

**Comment by SPS6** [comment] 2016-07-08 21:30
Ok I have reloaded it with the enchanced logging pbo and have some extra lines printed.  I would assume these are more informational than game breaking??

```
2016/07/08, 21:23:43 [8490,16.808,0,"XEH: PreInit started. v2.4.1.160606"]
2016/07/08, 21:23:43 Wrong init state
2016/07/08, 21:23:43 [XEH]: One or more children of class All do not support Extended Event Handlers. Fall back to loop.
2016/07/08, 21:23:43 [8490,16.904,0,"XEH: PreInit finished."]
```

```
2016/07/08, 21:23:50 [8492,23.563,0,"XEH: PostInit started. MISSIONINIT: missionName=TOD_TanoaLife_1000, missionVersion=52, worldName=Tanoa, isMultiplayer=true, isServer=true, isDedicated=true, CBA_isHeadlessClient=false, hasInterface=false, didJIP=false isLinux=false"]
2016/07/08, 21:23:50 String STR_CBA_FORMAT_NUMBER_DECIMAL_POINT not found
2016/07/08, 21:23:50 String STR_CBA_FORMAT_NUMBER_THOUSANDS_SEPARATOR not found
2016/07/08, 21:23:50 String STR_CBA_FORMAT_NUMBER_DECIMAL_POINT not found
2016/07/08, 21:23:50 String STR_CBA_FORMAT_NUMBER_THOUSANDS_SEPARATOR not found
2016/07/08, 21:23:50 String STR_CBA_FORMAT_NUMBER_DECIMAL_POINT not found
2016/07/08, 21:23:50 String STR_CBA_FORMAT_NUMBER_THOUSANDS_SEPARATOR not found
2016/07/08, 21:23:50 String STR_CBA_FORMAT_NUMBER_DECIMAL_POINT not found
2016/07/08, 21:23:50 String STR_CBA_FORMAT_NUMBER_THOUSANDS_SEPARATOR not found
2016/07/08, 21:23:50 [8492,23.572,0,"CBA_VERSIONING: cba=2.4.1.160606, "]
2016/07/08, 21:23:50 [8492,23.575,0,"XEH: PostInit finished."]
```

```
21:23:34 [0,6.994,0,"XEH: PreStart started."]
21:23:34 [0,7.021,0,"XEH: PreStart finished."]
21:23:34 [XEH]: Land_PowerLine_01_pole_junction_F does not support Extended Event Handlers! Addon: expansion
21:23:34 [XEH]: Land_PowerLine_01_pole_lamp_F does not support Extended Event Handlers! Addon: expansion
21:23:34 [XEH]: Land_PowerLine_01_pole_lamp_off_F does not support Extended Event Handlers! Addon: expansion
21:23:34 [XEH]: Land_PowerLine_01_pole_small_F does not support Extended Event Handlers! Addon: expansion
21:23:34 [XEH]: Land_PowerLine_01_pole_tall_F does not support Extended Event Handlers! Addon: expansion
21:23:34 [XEH]: Land_PowerLine_01_pole_transformer_F does not support Extended Event Handlers! Addon: expansion
21:23:34 [XEH]: Plane_Civil_01_base_F does not support Extended Event Handlers! Addon: expansion
21:23:34 [XEH]: B_CTRG_Miller_F does not support Extended Event Handlers! Addon: expansion
```

**Comment by commy2** [comment] 2016-07-08 23:47
Please upload a _full_ RPT file. Fragments don't help us. The last one was using different mods.

**Comment by commy2** [comment] 2016-07-08 23:47
Also, RC builds aren't supported either.

**Comment by Killswitch00** [comment] 2016-07-09 07:56
Initially, it was the RC build and MP sessions with CBA and two other sets of addons and a RPT file was provided. Further down the comments it appears to be only the RC and CBA 2.4.1.

> A blank mission with only CBA on it crashes player's clients when it is loaded as a multiplayer mission on a server. Remove CBA and no crashes... that is what makes me suspect that it may be CBA.
I have no shitty mods or any other type of mod loaded when it crashes, ONLY CBA.

Question: when this happens, does the server have CBA loaded or is it only the clients? (Does the server and client have the exact same set of addons loaded when the crash occurs?). 

Also, elaborate on what "a blank mission with only CBA on it" means. Is the provided mission file "Tanoa Fun" an example of "a blank mission with only CBA on it"? (Missions do not have "CBA on them")

**Comment by commy2** [comment] 2016-07-09 09:33
I edited the title so it matches the issue. Sorry BABACHORI , your thread has been hijacked.

**Comment by devShit** [comment] 2016-07-13 11:46
i got the same problem how you fix that
i run cba both side

**Comment by commy2** [comment] 2016-07-13 11:51
Hello, @devShit 
Please upload the RPT files (server and client). We cannot provide help without them.

**Comment by devShit** [comment] 2016-07-13 12:04
i can't place on pastebin sorry here it is
https://drive.google.com/open?id=0B3KT4NPa3I9FaDNicUJYN1h2bHM

**Comment by commy2** [comment] 2016-07-13 12:42
Your crash is not related to CBA. Also your game crashes at a completely different point as the one from SPS6.
If you think there is a incompatibility with some other addon, then please find out which one it is. The crash is not reproducable for me with only CBA enabled.

**Comment by devShit** [comment] 2016-07-13 12:44
excuse me 
what is sps6

**Comment by commy2** [comment] 2016-07-13 12:45
The guy with the furry and the british flag as avatar who posted in this issue.

**Comment by devShit** [comment] 2016-07-13 12:47
so FileServerActObj::MaintainMainThread() - Called from non main thread!
is not from cba right ?

**Comment by commy2** [comment] 2016-07-13 12:49
No.

**Comment by commy2** [comment] 2016-07-13 12:59
I'm closing this issue. It keeps getting hijacked.

Sorry but we don't have the time or ressources to debug crashes on your servers / with your mod repositories. Please try to reproduce issues with *only* CBA enabled first.
If you find a incompatibility, find out which addon exactly causes it.

**Closed by commy2** 2016-07-13 12:59 UTC
Labels: Need More Information
