### ISSUE TITLE
Cannot select certain Payload options

### ISSUE THREAD

**Issue by Sentinalza** [CBATeam/CBA_A3#964] opened 2018-08-20 13:08 UTC
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.0` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
- Cannot select certain Payload options on jets

**Steps to reproduce:**
- Place/spawn arma 3 vanilla jets, bombs are visible beneath jet, climb in and scroll through weapon list. Any type of bomb doesn't show up and can't be dropped or used
--

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by commy2** [comment] 2018-08-20 14:05
What jet and what weapon? How is it different from using the base game without mods?

**Comment by commy2** [comment] 2018-08-24 11:02
<details><summary>Using CBA</summary>

![https://i.imgur.com/QsSEDlZ.png](https://i.imgur.com/QsSEDlZ.png)
</details>
<details><summary>Minigun</summary>

![https://i.imgur.com/MMh6VfD.png](https://i.imgur.com/MMh6VfD.png)
</details>
<details><summary>Laser</summary>

![https://i.imgur.com/AnSjVuH.png](https://i.imgur.com/AnSjVuH.png)
</details>
<details><summary>AA Missile</summary>

![https://i.imgur.com/BZ6t9D8.png](https://i.imgur.com/BZ6t9D8.png)
</details>
<details><summary>HE Rocket</summary>

![https://i.imgur.com/xfIV6UN.png](https://i.imgur.com/xfIV6UN.png)
</details>
<details><summary>AP</summary>

![https://i.imgur.com/TzdUhqt.png](https://i.imgur.com/TzdUhqt.png)
</details>
<details><summary>Bombs</summary>

![https://i.imgur.com/Fgk7vDX.png](https://i.imgur.com/Fgk7vDX.png)
</details>
<details><summary>Top down AT</summary>

![https://i.imgur.com/OoRY0BX.png](https://i.imgur.com/OoRY0BX.png)
</details>

Seems like everything works as intended. I'm 99% sure OP's issue is a broken third party mod, and yes, some bugs only get revealed by using correctly configured mods like CBA. Still means the third party mod is broken. Please always test with vanilla as well as CBA only. Closing. Feel free to comment with new information should the issue persist, but please upload also a RPT and make sure you only use CBA, especially when the bug reports says CBA is supposedly the only used mod.

**Closed by commy2** 2018-08-24 11:02 UTC
