### ISSUE TITLE
Game freezing when hosting local server with large ui scale

### ISSUE THREAD

**Issue by siredgarhussein** [CBATeam/CBA_A3#1218] opened 2019-09-05 11:49 UTC
**Arma 3 Version:** `1.94` (stable)
**CBA Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
- Cannot host a server when CBA (steam workshop version) is loaded. Game freezes and subsequently crashes.

**Steps to reproduce:**
- load cba
- host an internet server with upnp enabled

**Where did the issue occur?**
- Self-Hosted Multiplayer

**RPT log file:**
- https://pastebin.com/7BVbNxfY

**Comment by dedmen** [comment] 2019-09-05 13:01
>- load cba
>- host an internet server with upnp enabled

Can't reproduce.

`-cpuCount=6 -exThreads=7 -enableHT -maxmem=6000 -maxvram=4000` These start parameters are all nonsense, you probably want to remove these.

**Comment by siredgarhussein** [comment] 2019-09-05 16:35
still crashes

**Comment by commy2** [comment] 2019-09-05 17:29
When does the game freeze?

**Comment by siredgarhussein** [comment] 2019-09-05 18:06
as soon as you host the server on the loading screen. It stays frozen for a while 5-10 minutes, then it crashes. you can't alt tab while it's frozen.

**Comment by commy2** [comment] 2019-09-05 18:16
So same as https://github.com/CBATeam/CBA_A3/issues/1180?

**Comment by siredgarhussein** [comment] 2019-09-05 18:23
yes, but I reinstalled cba, did nothing.

**Comment by commy2** [comment] 2019-09-05 18:23
The guy reinstalled the whole game as far as I can tell, not just a mod.

**Comment by siredgarhussein** [comment] 2019-09-05 18:26
ill try that

**Comment by commy2** [comment] 2019-09-05 18:28
Hoping for the best.

**Comment by commy2** [comment] 2019-09-07 13:23
Did it help?

**Comment by siredgarhussein** [comment] 2019-09-07 18:33
nope, still crashes

**Comment by commy2** [comment] 2019-09-07 18:59
Make a backup of your profile folders. Delete them. Try again.

They are found here by default:
```
"C:\Users\<WINDOWS_USER_NAME>\Documents\Arma 3"
"C:\Users\<WINDOWS_USER_NAME>\Documents\Arma 3 - Other Profiles"
```

**Comment by siredgarhussein** [comment] 2019-09-08 12:48
I found out why it happened, it's because my ui size was set to very large, it doesn't crash when it's set to normal.

**Comment by commy2** [comment] 2019-09-08 17:26
Interesting. I will try to reproduce! What screen size and pixel resolution do you use?

**Comment by commy2** [comment] 2019-09-08 22:18
Thanks, will be fixed in next release.

**Closed** 2019-09-08 22:29 UTC
Labels: Bug
