### ISSUE TITLE
High zoom optics broken on all LMGs

### ISSUE THREAD

**Issue by captainblaffer** [CBATeam/CBA_A3#159] opened 2015-09-20 14:40 UTC
CBA3 Version: v200150817-fixed

Mods:
    @CBA_A3

Description:

Most high zoom optics can not be used on any LMGs.
List:
- LMG_Zafir_F
- LMG_Mk200_F
- MMG_02_sand_F

When attempting to equip the scope in VA or via script, it won't appear.
Broken Scopes include:
- AMS
- DMS (optic_DMS)
- Kahila
- LRPS 
- MOS

Steps to reproduce:

Start Virtual Arsenal
Equip any lmg from list above 
Equip any of the optics above

Where did the issue occur?

    "Multiplayer", "Editor"

RPT log file:
n/a

**Comment by captainblaffer** [comment] 2015-10-09 08:14
Any word on this from the devs???

**Comment by dixon13** [comment] 2015-10-09 09:01
Can't reproduce with Kahila, LRPS, or the DMS. Scopes won't attach to any of the LMG's.

**Comment by dixon13** [comment] 2015-10-09 09:11
Found out this is intended behavior. Reference: CBA_A3/addons/jr/jr_classes.hpp Line 88.

**Comment by captainblaffer** [comment] 2015-10-09 11:22
These attachments work fine in default A3. Why should they be disabled? this is really annoying. Especially because one can't simply remove CBA from their modset, many other mods depend on it.

**Comment by dixon13** [comment] 2015-10-09 16:49
The above link that I posted has a comment on that same line that states, "// attachments that would not work well on machine guns". I'm guessing this is intentional for realism. IRL doesn't make sense to stick a high zoom optic on a LMG. The LMG's aren't made for sniping but rather suppression. IRL the gun would probably shake the scope off or shake the attachment so much that it would come loose and make it not accurate anymore.

**Comment by robalo** [comment] 2015-10-09 16:54
This was intended in JR and brought into CBA. Yes I see the point about not changing vanilla behavior. At the same time also think this is a vanilla bug because those big scopes look silly the way they clip through the weapon models when you reload, which you'd not even be able to do in real life since they'd make it impossible to open the belt feed cover. I am curious about what others think about this.

**Comment by MikeMatrix** [comment] 2015-10-09 19:26
I personally would just leave it like this. I feel like this is just a vanilla bug that never got fixed.

**Comment by jonpas** [comment] 2015-10-09 19:40
What @robalo and @MikeMatrix said.

**Comment by captainblaffer** [comment] 2015-10-09 19:47
"This was intended in JR and brought into CBA"
When running ASDG_JR 0.16, which is the latest version afaik, I am able to put all scopes on all LMGs.

"because those big scopes look silly the way they clip through the weapon models when you reload"
Partly true there is a visual glitch. But on the navid it looks fine. See video:
https://www.youtube.com/watch?v=WCOuZOl1ZQ8&feature=youtu.be

If you want to use realism as an argument, that's your decision. But please don't include such a big change in CBA, which is a requirement for many other mods, I can't just disable CBA if I don't like it.

This 'feature' also breaks many existing missions which feature scopes on LMGs. Even bigger mods like ACE don't break existing missions.
It would be really appreciated to keep this functionality the same as in arma 3, by allowing scopes on LMGs.

**Comment by jokoho48** [comment] 2015-10-09 19:54
that is a BI fault

**Comment by MikeMatrix** [comment] 2015-10-09 19:55
Well the consideration that should be made is, should CBA even Fix issues like those? It's more of a general project guideline question.

**Comment by jokoho48** [comment] 2015-10-09 19:55
i think that is not fixable if i remeber right this is model based(not fixable)

**Comment by PabstMirror** [comment] 2015-10-09 20:14
Could put this in optionals (unsigned) and let people use if they desire.
```
class CfgPatches
{
    class cba_jr_mgSniper
    {
        units[] = {};
        weapons[] = {};
        requiredVersion = 1;
        requiredAddons[] = {"cba_jr", "asdg_jointrails", "asdg_jointmuzzles"};
    };
};

class asdg_OpticRail1913_short;
class asdg_OpticRail1913_short_MG: asdg_OpticRail1913_short {
    delete compatibleItems;
};
```

The door on the Zafir/Negev clips through the scope when reloading.

![image](https://cloud.githubusercontent.com/assets/9376747/10404418/362abb46-6e98-11e5-908b-fa3e1ee92935.png)

**Comment by MikeMatrix** [comment] 2015-10-09 20:26
>`class cba_jr_mgSniper`

I love that class name :shipit:

**Comment by Calvin-McG** [comment] 2015-10-10 05:24
As captainblaffer says, CBA is a requirement for too many mods. Forcing a debatable realism change on what is effectively anyone using mods in any significant amount is not the place of CBA. 

This sort of change is a small patch, for what might not even be a problem for many users. And in the course of patching what may not even be an issue for some people those that actually want this functionality are left hanging. 

Of course there are some very good realism arguments that have been made above, but those that want more realism can't make decisions on behalf of those that don't.

An obvious solution would be to make this a separate mini-module that players and people in charge of community mod repos can decide on themselves.

**Comment by MikeMatrix** [comment] 2015-10-10 05:46
@Calvin-McG I think the opinion so far was pretty uniform that CBA doesn't do realism changes. What was to be considered though, is if this was a bug introduced by BI, and should something like that be fixed by something like CBA.
What @PabstMirror proposed is essentially what you just proposed as well. Introducing it as an optional component might be the most desireable solution to this, because the more I think about it, the more it makes sense for CBA not to modify behavior, only to complement behavior or supply functionality for modmakers.

**Comment by Calvin-McG** [comment] 2015-10-10 06:34
@MikeMatrix So far though the argument around it being a bug seems to be limited to the fact that it's realism is questionable, and that there are clipping issues. Just because it's not realistic doesn't mean it's a bug, and all that disabling things with clipping issues will do is remove any feature that didn't get animated quite perfectly.

**Comment by MikeMatrix** [comment] 2015-10-10 07:08
@Calvin-McG The argument being that the clipping issue exists, which is indicative that BI did not intent for this optic to be supported on that weapon.

**Comment by Calvin-McG** [comment] 2015-10-10 07:37
@MikeMatrix That's a pretty weak argument to justify a change like this. By the same argument BI also did not intend buildings, doors, rocks, and the V step to be present in the game.

**Comment by MikeMatrix** [comment] 2015-10-10 08:00
@Calvin-McG idk how you get to that conclusion, because that would mean that BI would have accidentally left configuration on buildings, doors, rocks and the V step (why is that even in this list?) to be the way so they would be on the map, even though it wasn't their intention.

The Optic clearly has that issue, as it either was accidentally misconfigured and that allows it to be used on top of the AR, or it hasn't been animated properly, which makes it clip through the weapon. I think considering we're speaking of adding high magnification optics on top of automatic rifles, the first option is the more likely one.

With that conclusion in mind, the question remains, if CBA should patch something like that or not.
My standpoint at this moment is, that if we were to provide a patch like that, it should be as an optional change, as CBA is a library mod, and as such shouldn't alter behavior unless it is to provide functionality to enable other mods to do what they do.

**Comment by dixon13** [comment] 2015-10-10 08:03
Why make an optional pbo for the patch when ACE3 can just put it in their mod? Like @Calvin-McG said before, this mod is for functionality and not realism. If it's for realism, then hand it off to ACE and let them deal with it.

**Comment by Imperum** [comment] 2016-01-15 13:25
This is something that comes out of the base game, in my opinion a "support" mod should not force these kind of changes. If the devs find it something they desire, make it optional for the players that don't like it so they can atleast use CBA without any changes. Or move it to ACE as suggested by others. As so many other mods depend on this mod, it should not make such big game-changing features. Maybe give it its own module/separate part and keep the basegame features. 

I wan't to use this mod, but this very little change keeps me from enjoying the game as before. I just love my adjustable zoom scopes. Hope that something will be done with this "issue".

**Closed** 2016-01-23 14:35 UTC
Labels: bug
