### ISSUE TITLE
Contact CBA JointRails Compatibility

### ISSUE THREAD

**Issue by NorXAengell** [CBATeam/CBA_A3#1283] opened 2020-01-17 15:13 UTC
Could you add Contact weapons to use CBA JointRails classes.

Like this mod : https://steamcommunity.com/sharedfiles/filedetails/?id=1888068830&searchtext=

Thx guys :)

**Comment by dedmen** [comment] 2020-01-18 14:08
I'll never understand why people don't just make a pull request, but instead go to the effort to make a full sub-mod that does the same.

**Comment by commy2** [comment] 2020-01-18 14:20
Yeah, now I am stuck here unable to look at the code, because the workshop doesn't work for me and I never used it before.

**Comment by commy2** [comment] 2020-01-18 14:21
Also, isn't this the same as #1190?

**Comment by Drofseh** [comment] 2020-01-18 17:04
> Also, isn't this the same as #1190?

No, that one is for magwells and this one is for rails.

**Comment by commy2** [comment] 2020-01-18 17:21
And where's the difference? Practically I mean?

**Comment by jonpas** [comment] 2020-01-18 19:50
That you need to add different classes? :thinking:

**Comment by commy2** [comment] 2020-01-19 12:22
@NorXAengell 
I checked ingame and the Promet ("contact weapon") can use all base game items.

If you have a 3rd party mod that has optics that are incompatible with the weapon, then that is because the Promet uses the MuzzleSlot_65 and CowsSlot_MSBS65 attachment classes. **That 3rd party mod author has to add their optics to those classes as well as the CBA JR classes**.

The addon you posted (from the Steam site) in fact **breaks** all addons that correctly add their attachments to the MuzzleSlot_65 etc. class and don't bother with CBA.

The issue is basically the same as this: https://github.com/CBATeam/CBA_A3/issues/1258#issuecomment-557842679, except that these weapons are obviously not covered by the legacy component.

**Closed by commy2** 2020-01-19 12:22 UTC
Labels: Task
