### ISSUE TITLE
Shared version display on main menu doesn't show any more

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [CBATeam/CBA_A3#1114] opened 2019-04-09 23:10 UTC
**Arma 3 Version:** Latest stable` (stable / rc / dev)
**CBA Version:** `3.10.1` stable latest 

**Mods:**
```
- CBA_A3
-ACE 3 (latest updated)
```

**Description:**
- Shared version display (https://github.com/CBATeam/CBA_A3/wiki/Versioning-System#shared-version-display-optional) doesn't show anymore at bottom right, tested with only cba and Ace and the with some other mods that use it.

**Steps to reproduce:**
-Start game

**Where did the issue occur?**
- at game start

**RPT log file:**
  https://pastebin.com/HYWzGvCq

**Comment by dedmen** [comment] 2019-04-12 18:22
Is this part of the "advertisement" that was removed maybe?

**Comment by commy2** [comment] 2019-04-12 19:51
Yes. https://github.com/CBATeam/CBA_A3/pull/1073

I think it is superfluous, since you can hover over the mod icons on the left and it will show the version.

**Comment by MisterHLunaticwraith** [comment] 2019-04-12 22:42
Nah it was cool, and useful sometimes + the ACE 3 one had bananas falling around when you clicked it.

**Comment by commy2** [comment] 2019-04-21 10:09
Close?

**Comment by thojkooi** [comment] 2019-04-21 10:28
Thanks for reporting. This is intended behaviour since #1073. As such I will close this. Thanks for your time.

**Closed by thojkooi** 2019-04-21 10:28 UTC
