### ISSUE TITLE
CBA_fnc_taskPatrol

### ISSUE THREAD

**Issue by Maffaxxx** [CBATeam/CBA_A3#499] opened 2016-09-07 18:04 UTC
**Arma 3 Version:** 1.62 stable 
**CBA Version:** `3.0.0` stable

**Mods:**
- `@CBA_A3 - @ACE`

**Description:**
- CBA_fnc_taskPatrol (both script and module) generate an error in RPT:

18:44:18 File x\cba\addons\ai\fnc_addWaypoint.sqf, line 3
18:44:18 Error in expression < "x\cba\addons\ai\fnc_addWaypoint.sqf"

params [
"_group",
"_position",
["_radiu>
18:44:18   Error position: <params [
"_group",
"_position",
["_radiu>
18:44:18   Error Params: Type Array, expected String
18:44:18 File x\cba\addons\ai\fnc_addWaypoint.sqf, line 3
18:44:18 Error in expression < "x\cba\addons\ai\fnc_addWaypoint.sqf"

**Steps to reproduce:**
- module: place a module in the editor, synch it to one or more groups, check .rpt
- init script: place a script in the init field of a unit: [this, this, 300, 7, "MOVE", "AWARE", "YELLOW", "FULL", "STAG COLUMN", "", [3,6,9]] call CBA_fnc_taskPatrol;

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer) / 

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

[arma3_2016-09-07_18-05-48.zip](https://github.com/CBATeam/CBA_A3/files/460001/arma3_2016-09-07_18-05-48.zip)

Note: script&module still work properly, but they spam the RPT horribly.

**Comment by commy2** [comment] 2016-09-07 19:13
@SilentSpike 
was this already fixed in https://github.com/CBATeam/CBA_A3/pull/440 ?

**Comment by commy2** [comment] 2016-09-07 19:28
I can't reproduce on latest master. Waiting for Silents answer. (Reminder to myself to add this to the changelog)

**Comment by Maffaxxx** [comment] 2016-09-07 19:35
try placing more units. when i tried one group only once it looked fine, but when you have several (as in trying to reproduce a civilian city) you got problems. more than 4 groups should do the trick. someone pointed out to me that maybe it is due to a lacking Z parameter in the second position of the array, the placement one (no idea what he was talking about tho).

**Comment by commy2** [comment] 2016-09-08 02:23
Can you upload an example mission? Preferably with anything striped away that isn't vanilla Arma?

**Comment by SilentSpike** [comment] 2016-09-08 09:04
@commy2 I can't say I ever encountered this error in all of my testing for that PR

It looks like that's an outdated function though because in the latest version the `params` has `["_position",[]]` not just `"_position"`

**Comment by commy2** [comment] 2016-09-08 09:08
Yeah, even before your PR, it was:
`params ["_group", ["_position",[]], ["_radius",50,[0]] ...`

instead of
`params ["_group", "_position", ["_radiu ...`
as shown in this RPT.

**Comment by commy2** [comment] 2016-09-08 09:13
NVM. This is a follow up and the error happens in ´addWaypoint`

https://github.com/CBATeam/CBA_A3/blob/master/addons/ai/fnc_addWaypoint.sqf#L35

**Comment by SilentSpike** [comment] 2016-09-08 09:14
Just mentally going through `taskPatrol` now and can't say I see anything wrong with what it's doing and passing into `addWaypoint`.

**Comment by commy2** [comment] 2016-09-08 09:15
Same, although I must say, that I dislike how the arguments are handled.

**Comment by SilentSpike** [comment] 2016-09-08 09:17
You mean how it implicitly just passes them on to `addWaypoint` to sort out?

**Comment by commy2** [comment] 2016-09-08 09:17
Exactly

**Comment by commy2** [comment] 2016-09-08 09:22
Meh. We can keep it, but I'd like to figure this problem out.

**Comment by commy2** [comment] 2016-09-08 09:25
>try placing more units. when i tried one group only once it looked fine, but when you have several (as in trying to reproduce a civilian city) you got problems. more than 4 groups should do the trick

I placed 20 NATO rifle squads and put the line in every squad leader. It's crawling everywhere, but no error in sight.

**Comment by Maffaxxx** [comment] 2016-09-08 12:26
I tried several times to reproduce in a blank mission today but i couldnt. :-/

i understood what happened. I dont think i have done this, so search me on HOW it actually happened, but different randompatrol functions got in both the init field of the unit AND in the object init of its own group. I suppose one glitchy save made a mess and displaced code around. 

I am not certain this is what caused the error, because i never meant to put code in the group init field in the first place, but it got there somehow. Now, i took away all the codes, and replaced them one by one, and it seems working.

**Comment by commy2** [comment] 2016-09-08 15:11
So if you put the code into the group init box _and_ into the squad leaders init box, this error happens?

**Comment by Maffaxxx** [comment] 2016-09-08 15:17
i am not *sure*. i found different codes in the boxes, i mean the same function, but with different parameters. Sometimes a line like "this stop true" would appear in the object init of a unit that had waypoints laid out. No idea how it got there, i never write that line myself. 

Really no idea how this error could have happened. now i've deleted everything and redone from scatch and the error seems to have disappeared. probably it's best treating it as a one time error and close the ticket. if it comes again ill be sure to notify you with more relevant data.

**Comment by commy2** [comment] 2016-09-08 15:49
ok. false alarm then.

**Closed by commy2** 2016-09-08 15:49 UTC
Labels: Need More Information
