### ISSUE TITLE
Possibility to cancel CBA module

### ISSUE THREAD

**Issue by PierreMGI** [CBATeam/CBA_A3#561] opened 2016-11-30 20:45 UTC
**Arma 3 Version:** `1.64` (stable)
**CBA Version: Steam updated

**Mods:**
- `@CBA_A3`

**Description:**
- This is not an issue. I was redirected on this page, clicking "new request functionality".

My aim is to make the patrol & defend modules only when there is no player on the concerned group.
In MP, (or along with teamswitch in SP), two cases:
- if full AIs group, the group acts along with the patrol (or defend) module,
-  if JIP or teamswitch into the group, stop the patrol (defend) module.

The reason is there are some AI units (not all??) who don't follow orders any more, what ever the order (or scripted move) could be. Even if desynchronized (by script with SynchronizeObjectsRemove) the group keeps waypoints. Delete all these waypoints, some units seem stuck between several behaviors, restless raising/lowering their gun.

I guess my request is something about terminate a function, but which one and how to do it?
Thanks

**RPT log file:**
none.

**Comment by commy2** [comment] 2016-12-02 16:37
You could use these functions instead.
https://github.com/CBATeam/CBA_A3/blob/master/addons/ai/fnc_taskPatrol.sqf
https://github.com/CBATeam/CBA_A3/blob/master/addons/ai/fnc_taskDefend.sqf

>Delete all these waypoints, some units seem stuck between several behaviors, restless raising/lowering their gun.
I think that is a duplicate of #551

**Comment by PierreMGI** [comment] 2016-12-02 17:44
I did some tests. The task patrol (module or function) needs  a script like:
 <dofollow (leader) and if stopped (_unit) then domove (leader position)>
Disregard the syntax, it's just an explanation - to make all units back in a bearable attitude. This is probably due to a vanilla behavior for groups.
On the other hand the defend module or function breaks some units behaviors (along with vanilla group hierarchy and sub-command) due to a disableAI "path" which seems to be impossible to override.

**Comment by SilentSpike** [comment] 2016-12-24 10:44
For the defend module `_unit enableAI "PATH"` will re-enable movement of halted units.

Task patrol is just a set of waypoints so there should be no need to check for stopped units etc. The function `CBA_fnc_clearWaypoints` was actually added and is used at the start of all task functions to make them re-usable (with the exception of defend currently) by clearing all of their current waypoints.

Perhaps we should also add an `enableAI "PATH"` to the start of the task functions so that they can be applied after a task defend.

**Closed** 2017-01-18 16:06 UTC
Labels: question
