### ISSUE TITLE
CBA 2.4.1 and TFR (APEX Preview build)

### ISSUE THREAD

**Issue by Pydrex** [CBATeam/CBA_A3#400] opened 2016-06-24 18:20 UTC
Hello Folks,

I have opened an issue over on TFRS Git too (https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1077) 

When you load into the game with CBA 2.4.1 and TFR loaded TFR does not connect you or move you into the server, If you use an old build 2.3.1 it works however on APEX You get the string error which crashes your game.

19:02:59 String STR_CBA_FORMAT_NUMBER_DECIMAL_POINT not found
19:02:59 String STR_CBA_FORMAT_NUMBER_THOUSANDS_SEPARATOR not found
19:02:59 String STR_CBA_FORMAT_NUMBER_DECIMAL_POINT not found
19:02:59 String STR_CBA_FORMAT_NUMBER_THOUSANDS_SEPARATOR not found
19:02:59 String STR_CBA_FORMAT_NUMBER_DECIMAL_POINT not found
19:02:59 String STR_CBA_FORMAT_NUMBER_THOUSANDS_SEPARATOR not found
19:02:59 String STR_CBA_FORMAT_NUMBER_DECIMAL_POINT not found

**Comment by sargken** [comment] 2016-06-24 18:29
I use CBA and TFR and have no issues.

**Comment by Pydrex** [comment] 2016-06-24 18:39
On Preview build?

**Comment by Pydrex** [comment] 2016-06-24 18:39
This is on the Sneak Preview build

**Comment by sargken** [comment] 2016-06-24 18:40
Negative sorry i didn't realize you were on apex build.

**Comment by Pydrex** [comment] 2016-06-24 18:41
No problem, Its rather annoying was working fine till the 5gb update A3 Done the other day

**Comment by jonpas** [comment] 2016-06-24 18:47
This is already fixed on master. Thanks for the report though.

**Comment by Pydrex** [comment] 2016-06-24 18:47
Is there a way I can grab the fix for my server?

Thanks <3

**Comment by commy2** [comment] 2016-06-24 18:50
@Pydrex jonpas was refering to the missing strings, which have most likely nothing to do with TFAR.

Can you please upload a _full_ RPT of the session with the error happening?
Keep in mind that development branches are not supported by us for technical reasons.

**Comment by jonpas** [comment] 2016-06-24 18:50
~~You can build CBA yourself, refer to the wiki. I am not sure what the license says for distributing your own build though.~~ What @commy2 said, I honestly didn't even read the first part, my bad!

I suggest you simply don't use Apex branch for your server though, for testing yes, but not a server people play on.

**Comment by Pydrex** [comment] 2016-06-24 18:52
19:09:43 Attempt to override final function - bis_fnc_missionflow
19:09:43 [12641,45.613,0,"XEH: PreInit started. v2.3.1.160220. MISSIONINIT: missionName=ArmaNetwork, worldName=Tanoa, isMultiplayer=true, isServer=false, isDedicated=false, hasInterface=true, didJIP=false"]
19:09:44 [XEH]: Usage of deprecated Extended Event Handler "fired". Use "firedBIS" instead. Path: @AN_Tanoa\bin\config.bin\Extended_Fired_EventHandlers\Man.
19:09:44 [12641,47.058,0,scalar NaN,"CBA: Exporting BIS_fnc_errorMsg to missionNamespace"]
19:09:44 Attempt to override final function - bis_fnc_errormsg
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error in expression <>
19:09:44   Error position: <>
19:09:44   Error 3 elements provided, 2 expected
19:09:44 Error in expression <rced"); };






{
_xCode = uinamespace getvariable _x;

if (isNil "_x") then {
>19:09:44 File x\cba\addons\common\init_functionsModule.sqf, line 36

19:09:44   Error position: <getvariable _x;

if (isNil "_x") then {
>
19:09:44   Error 3 elements provided, 2 expected
19:09:44 Error in expression <rced"); };






{
_xCode = uinamespace getvariable _x;

if (isNil "_x") then {
>19:09:44 File x\cba\addons\common\init_functionsModule.sqf, line 36

19:09:44 Error: Mismatched Begin/EndContexts
19:09:44   Error position: <getvariable _x;

if (isNil "_x") then {
>
19:09:44   Error 
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error: Mismatched Begin/EndContexts
19:09:44 Error: Mismatched Begin/EndContexts
=======================================================
-------------------------------------------------------
19:09:44 FileServerActObj::MaintainMainThread() - Called from non main thread!
Exception code: C0000005 ACCESS_VIOLATION at 017272B2
graphics:  D3D11, Device: NVIDIA GeForce GTX TITAN X

**Comment by Pydrex** [comment] 2016-06-24 18:52
Hi I looked through and found the error

**Comment by commy2** [comment] 2016-06-24 18:54
This looks very interesting, but is not a full RPT file.

**Comment by Pydrex** [comment] 2016-06-24 18:55
http://pastebin.com/Z1wX5Mv5

**Comment by Pydrex** [comment] 2016-06-24 18:56
I was renaming TFR different versions of CBA etc but nothing loaded in TFR properly. It would give the options to change voice yell/whisper/normal modes etc but didn't move me in channels or if it did it moved to TFR then straight back out.

**Comment by commy2** [comment] 2016-06-24 19:04
- this RPT is not showing the latest version of CBA. This RPT has v2.3.1, but the latest version is v2.4.1
We do not support legacy versions.
- the CBA folder you get with the TFAR is very outdated and is no longer supported. Just ignore or delete it and only use the latest one provided here.
- is the error reproducable with __only__ CBA + TFAR on a __scriptless empty mission__? You are loading additional addons which cause many error messges in this RPT file
- it is not adviced to use the development branches of Arma for playing. They are meant for testing. Expect all kinds of bugs, whether they are related to CBA or not.

**Comment by Pydrex** [comment] 2016-06-24 19:13
Hi, I tested multiple versions sorry for the incorrect RPT.

I know Its a test build but I wanted to test out our mods on Tanoa etc and noticed this was an issue,  Just wanted to raise it with you guys as obviously Apex is fast approaching incase any bugs needed sorting by then.

I am using the Steam CBA_A3 and the 0.9.8 latest TFR (abiet october 2015)

Just incase its any help but I don't see any error par the .dll at the end, But it could just be Arma screwed up something or even blocked the .dll in Battleye.
[arma3_2016-06-24_19-15-36.txt](https://github.com/CBATeam/CBA_A3/files/332415/arma3_2016-06-24_19-15-36.txt)



`

**Comment by commy2** [comment] 2016-06-24 19:20
I see. Error is that TFAR is not working as expected.

Please try the following:
- try to reproduce this error without `@AN_Tanoa` on an newly created (scriptless mission)

Thanks

["processPlayerPositionsHandler", "onEachFrame", "TFAR_fnc_processPlayerPositions"] call BIS_fnc_addStackedEventHandler;

**Comment by commy2** [comment] 2016-06-24 19:21
I see. Error is that TFAR is not working as expected.

Please try the following:
- try to reproduce this error without `@AN_Tanoa` on an newly created (scriptless) mission

Thanks

**Comment by Pydrex** [comment] 2016-06-24 19:36
[arma3_2016-06-24_20-32-55.txt](https://github.com/CBATeam/CBA_A3/files/332464/arma3_2016-06-24_20-32-55.txt)

Hi Guys,

I tried this but have errors on this branch, TFR did move me briefly but on second try it didn't, However i have spotted some errors on this rpt.

**Comment by commy2** [comment] 2016-06-24 19:40
This RPT shows a single player game. Is TFAR supposed to move you in SP games too? Never heard of that.

`20:33:46 [7056,50.577,0,"XEH: PostInit started. MISSIONINIT: missionName=tempMissionSP, missionVersion=52, worldName=VR, isMultiplayer=false, isServer=true, isDedicated=false, CBA_isHeadlessClient=false, hasInterface=true, didJIP=false isLinux=false"]`

**Comment by Pydrex** [comment] 2016-06-24 19:45
Yeah it does usually too. I can through it up in a live enviroment too if needed?

**Comment by commy2** [comment] 2016-06-24 19:47
Yeah. A server with a new mission. IDK if TFAR requires you to set some variables for this moving-channel behaviour. If that is the case then add that script to the new mission.

**Comment by Pydrex** [comment] 2016-06-24 19:48
However it did move me in this enviroment as singleplayer whilst on TS, At least once anyway. However I could not hear radio sounds and when I pressed Caps for radio etc you usually here a "Psst"

**Comment by Pydrex** [comment] 2016-06-24 20:24
Ok,

I just confirmed on a normal blank mission this is working with TFR. Moving and voice both work.

I loaded in @AN_Tanoa and it also worked, However I loaded in the server mod and its mission then it stopped working, This all all done on the VR Map, I doubt Tanoa map has anything to do with this?

**Comment by commy2** [comment] 2016-06-24 20:28
I don't think so either. Please use this final test:

- add this script on the first line of the `init.sqf` file of the mission:
```
0 spawn {
    sleep 10;
    ["commy_fixOEF", "onEachFrame", {}] call BIS_fnc_addStackedEventHandler;
};
```

and try again with all addons.

**Comment by commy2** [comment] 2016-06-24 20:29
Note that TFAR scripting might be delayed by 10 seconds, but it might work after that.

**Comment by Pydrex** [comment] 2016-06-24 20:43
Hi Commy,

Running this moved me into TFR and radios seemed to work as expected, I did have to run     ["commy_fixOEF", "onEachFrame", {}] call BIS_fnc_addStackedEventHandler; once or twice in the debug console so maybe just need to change the spawn.

Hopefully this gives you some idea or what is happening

**Comment by Pydrex** [comment] 2016-06-24 20:48
Correction, Using the spawn moved me back and forth over and over, Whilst I was in the channel I could action as normal.

**Comment by Pydrex** [comment] 2016-06-24 20:49
If I spammed BIS_fnc_addStackedEventHandler in the console it worked

**Comment by commy2** [comment] 2016-06-24 20:51
Yes, I now know exactly what is happening.

- TFAR is using an `onEachFrame` to properly work. This is a piece of code that will be repeated every frame and probably does some kind of polling.

https://github.com/michail-nikolaev/task-force-arma-3-radio/search?utf8=%E2%9C%93&q=BIS_fnc_addStackedEventHandler

- The `onEachFrame` SQF command (https://community.bistudio.com/wiki/onEachFrame) is not "stackable". You can only add one function at any time, so you'd get compatibility problems if you use it in two places. Note the green warning on the BI wiki.

- To circumvent this, one has to use `BIS_fnc_addStackedEventHandler` instead of `onEachFrame` directly. This is a wrapper / framework that can handle multiple functions for `onEachFrame` (and other event handlers) at once.

- TFAR uses this method so it's fine.

- Either a script in `@AN_Tanoa` or your mission uses the `onEachFrame` directly which overwrites all other event handlers, including those added via `BIS_fnc_addStackedEventHandler`

- My script adds another event handler (one that does nothing) just to reapply all events added correctly with `BIS_fnc_addStackedEventHandler`. This means though that the one added with `onEachFrame` will be overwritten. Some other thing will therefore break with this fix.

**Comment by Pydrex** [comment] 2016-06-24 20:55
Would this cause it:

ThreadList = [];
ThreadDelays = [];
ThreadTimer = time;
ThreadSleep = 0.01;
ThreadID = 10000;
[] spawn
{
	waitUntil {!isNil "PlayerPrep"};
	diag_log "Client Main Thread started";
	while {true} do
	{
		if !(ThreadList isEqualTo []) then
		{
			{
				if (ThreadTimer > (((_x select 1) + (_x select 0)) - ThreadSleep)) then
				{
					(_x select 3) call (_x select 2);
					_x set [1, time];
					if !(_x select 5) then
					{
						[_x select 4] call life_fnc_vunurepru;
					};
				};
			}
			forEach ThreadList;
		};
		onEachFrame {};
		ThreadTimer = time;
		uiSleep ThreadSleep;
	};
};

**Comment by commy2** [comment] 2016-06-24 20:55
Solution for this problem:
Find the rogue `onEachFrame` command and replace it with `BIS_fnc_addStackedEventHandler`

```
onEachFrame {<My Code>};
->
["Tag_MyUniqueEventHandlerName", "onEachFrame", {<My Code>}] call BIS_fnc_addStackedEventHandler;
```

**Comment by commy2** [comment] 2016-06-24 20:55
>onEachFrame {};
Yes! That's it.

**Comment by Pydrex** [comment] 2016-06-24 20:57
Ah, What would you suggest then using ["commy_fixOEF", "onEachFrame", {}] call BIS_fnc_addStackedEventHandler; or changing out onEachFrame {}; for something else?

**Comment by commy2** [comment] 2016-06-24 20:58
Definitely replace __all__ `onEachFrame {};` with `BIS_fnc_addStackedEventHandler` like I described here: https://github.com/CBATeam/CBA_A3/issues/400#issuecomment-228459638

**Comment by commy2** [comment] 2016-06-24 20:58
Btw. I added code tags (```) to your post, so the code is readable.

**Comment by Pydrex** [comment] 2016-06-24 21:04
I will give it a go and let you know.

**Comment by Pydrex** [comment] 2016-06-24 21:08
Ok, Changing this and commenting it out I seem to still get kicked in and out of TFR. If I run ["ThreadListFix", "onEachFrame", {}] call BIS_fnc_addStackedEventHandler; for example in debug console it will leave me there. I am wondering could a removeEventHandler somewhere be killing this too?

**Comment by Pydrex** [comment] 2016-06-24 21:09
Would dialogs like (findDisplay 2700) displayRemoveAllEventHandlers "KeyDown"; catch this?

**Comment by commy2** [comment] 2016-06-24 21:10
>I am wondering could a removeEventHandler somewhere be killing this too?

I don't think so. This overwriting behaviour is only from `onEachFrame`

>Would dialogs like (findDisplay 2700) displayRemoveAllEventHandlers "KeyDown"; catch this?

No. Display event handlers are unrelated to the `onEachFrame` event handler.

**Comment by commy2** [comment] 2016-06-24 21:12
You can add the following function on top of your init.sqf to see if you eliminated all rogue `onEachFrame`:

`["commy_test", "onEachFrame", {systemChat str diag_frameNo}] call BIS_fnc_addStackedEventHandler;`

Only if this prints the current frame number into the chat every frame, the OEF event handlers are working.

**Comment by Pydrex** [comment] 2016-06-24 21:14
This ran then stopped after say 3/5 frames. Must have something else hidding in here!

**Comment by Pydrex** [comment] 2016-06-24 21:15
Note, when I run this TFR moves me. Is this expected behaviour ?

**Comment by commy2** [comment] 2016-06-24 21:15
Seems like another rogue `onEachFrame` is running after those 3-5 frames.

**Comment by commy2** [comment] 2016-06-24 21:16
>Note, when I run this TFR moves me. Is this expected behaviour ?

Yes. It will restore all `onEachFrame` event handlers added with `BIS_fnc_addStackedEventHandler` including those from TFAR.

**Comment by Pydrex** [comment] 2016-06-24 21:24
Hmm. Is there any other way to call this function for OnEachFrame, Literally searching all over but can't find this lil bugger!

**Comment by commy2** [comment] 2016-06-24 21:25
>Is there any other way to call this function for OnEachFrame, Literally searching all over but can't find this lil bugger!

Unfortunately no. Welcome to Arma.

I know a way you can band-aid fix this. This is a very suboptimal way and hacky way. You might want to consider it in case you cannot find the last source of your error.

```
private _dummyTrigger = createTrigger ["EmptyDetector", [0,0,0], true];
_dummyTrigger setTriggerStatements ["
    [""commy_fixOPC"", ""onEachFrame"", {}] call BIS_fnc_addStackedEventHandler;
    false
", "", ""];
```

This creates a trigger that sets a dummy OEF event handler every 0.5 seconds.

**Comment by commy2** [comment] 2016-06-24 21:26
>Is there any other way to call this function for OnEachFrame, Literally searching all over but can't find this lil bugger!

Unfortunately no. Welcome to Arma.

I know a way you can band-aid fix this. This is a very suboptimal way and hacky way. You might want to consider it in case you cannot find the last source of your error.

```
if (isServer) then {
    private _dummyTrigger = createTrigger ["EmptyDetector", [0,0,0], true];
    _dummyTrigger setTriggerStatements ["
        [""commy_fixOPC"", ""onEachFrame"", {}] call BIS_fnc_addStackedEventHandler;
        false
    ", "", ""];
};
```

This creates a trigger that sets a dummy OEF event handler every 0.5 seconds.

**Comment by Pydrex** [comment] 2016-06-24 21:33
Is there a way I can donate to the CBA project?

**Comment by commy2** [comment] 2016-06-24 21:38
So, I guess we solved it? ; - )

I don't think we have a place for donations.

**Comment by Pydrex** [comment] 2016-06-24 21:44
Looks like it works, But I really appreicate the time you've dedicated to helping me. Probs to you guys, Truly a refreshing experience in the Arma community. Most people are like "F u sort it urself" "not our problem"

**Comment by commy2** [comment] 2016-06-24 21:46
Thanks.
I'll close this, because it isn't anything wrong with CBA directly.

**Closed** 2016-06-24 21:46 UTC
Labels: invalid

**Comment by devShit** [comment] 2016-07-13 14:56
ya i'm pretty sure its not about cba be cause i have remove CBA out both side so. the log still given

**Comment by commy2** [comment] 2016-07-13 15:58
@devShit 
I suggest you create a ticket on the BI feedback tracker. They can evaluate why the game actually crashes.
https://feedback.bistudio.com/
