### ISSUE TITLE
Incorrect Name And Description For 7.62x51mm 150 Round Belt Box

### ISSUE THREAD

**Issue by LuizBarros99** [CBATeam/CBA_A3#1147] opened 2019-05-23 13:53 UTC
**Arma 3 Version:** `1.92145639` (as of 23/05/2019)` (stable branch)
**CBA Version:** `3.11.2` (STEAM WORKSHOP version (Version latest as of the same date)

**Mods:**
```
- CBA_A3
-ArmaForces - GM CBA Mag Compat
-Enhanced Movement
-Enhanced Soundscape
-@Grenade Window Breaker(mod Version)
-JSRS Sound Mod- 6.19.0127
-JSRS Sound Mod- 6.19.0126-Reloading Sounds
-@Ragdoll Effects Overhaul (Realistic)
-@Unofficial JSRS Global Mobilization- Cold War Germany Sound Patch 
```
**DLC:**
```
-Global Mobilization
```

**Description:**
- The "Old Zafir" 7.62x51 belts with 150 rounds are indistinguishable from the "Current Zafir" 7.62x54 Belts. It even says that the can be used on the "Current Zafir", but are unable to be used. Also the 7.62x51 is said to be 7.62x54, which makes distinguishing the two belt types impossible unless with a 7.62x54 or 7.62x51 belt fed MG.

**Steps to reproduce:**
- Take a MG whose magwell is made compatible with the 7.62x51 Zafir belt in the Virtual Arsenal and take some of the "Old Zafir" belts. Then take the "Current Zafir" and take some of its belts.

The "OLD Zafir" belts are completely indistinguishable from the "Current" ones, they are even listed as 7.62x54 and said to be used in the (presumabily "CURRENT") Zafir!

**Where did the issue occur?**
- This was first seen on the Virtual Arsenal, but can affect about any mission that uses MGs of both magwells, as players will seek ammo that they have no way of knowing if it will work in their guns

**RPT log file:**
- I was unable to find them. Yes, I am a noob.

**Comment by TrainDoctor** [comment] 2019-05-23 15:55
1. This is likely related to the mod you listed called ```ArmaForces - GM CBA Mag Compat```.
    * This mod has no direct connection to CBA.
2. If this did have a direct connection to CBA I would ask that you repeat your steps running A3 with GM, and CBA on their own for the sake of reproducing the issue in an easier to debug vacuum. 

If it's determined that the belts in question are from the mod I mentioned, then this issue should be closed and marked as wontfix/invalid.

**Comment by commy2** [comment] 2019-05-23 16:20
Opened the Arsenal with just CBA_A3
![https://i.imgur.com/bGFjyMz.png](https://i.imgur.com/bGFjyMz.png)

**Comment by commy2** [comment] 2019-05-23 16:21
>I was unable to find them. Yes, I am a noob.

They are under `%LOCALAPPDATA%\Arma 3`.

**Comment by veteran29** [comment] 2019-05-23 16:41
Take a look at this CUP ticket: https://dev.cup-arma3.org/T3266

The issue is that as some point BI changed Zafir to use `x54R` mags instead of `x51`. However they've left old classes for compatiblity I guess. CBA Exposes these mags via CBA JAM Magwells to other addons (so it kinda makes them usable again). 

The issue is that BI have changed description of `x51` variant and it states that it's `x54R` caliber. This confuses users and if any addon (like mine [ArmaForces - GM CBA Mag Compat](https://gitlab.com/armaforces/armaforces_gm_cba_mag_compat)) uses it for compatibility it makes users think that addon is faulty and allows wrong caliber mags in a weapon.

I think it is reasonable to change description of said mags to correctly state their caliber to not confuse users.

**Comment by veteran29** [comment] 2019-05-23 22:45
It seems the wrong description is there because BI just changed content of their translation keys and reused them for both x51 and x54R mags. (eg. `STR_A3_CfgMagazines_150Rnd_762x51_Box_Tracer1` for tracer box of both calibres)

**Comment by commy2** [comment] 2019-05-24 07:48
Thanks for the report and the pull request guys :P
;)

**Closed** 2019-05-25 17:39 UTC
Labels: Bug
