### ISSUE TITLE
Addon Settings List type tooltip error

### ISSUE THREAD

**Issue by mgkid3310** [CBATeam/CBA_A3#1298] opened 2020-02-19 13:23 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96.146113 profiling` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.14.0.200207 stable` [e.g. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
CBA addon settings tooltip error
```
22:11:52 Error in expression <e _label = (_settingData param [1, []]) param [_defaultValue, ""];

if (isLocali>
22:11:52   Error position: <param [_defaultValue, ""];

if (isLocali>
22:11:52   Error Type Bool, expected Number
22:11:52 File x\cba\addons\settings\gui_createCategory.sqf..., line 139
```

**Steps to reproduce:**
- add list type cba addon setting, with non-number values for each selection
- open cba addon settings

**Expected behavior:**
no errors

**Where did the issue occur?**
- Editor (Singleplayer)

**Log Files:**
- https://pastebin.com/jX453tPN

**Additional context:**
It seems the error itself does not hurt gameplay
Error seems to have occured from: https://github.com/CBATeam/CBA_A3/commit/6c84b7ed3cea93d6405c1daa7bb2640739f1c527#diff-913ce4a178ff741f892f9c9dee7924b5
`_defaultValue` variable for list type setting is not guaranteed to be a number type.

**Screenshots:**
N/A

**Comment by veteran29** [comment] 2020-02-19 13:25
Duplicate of #1295 fixed in #1296

**Closed** 2020-02-19 13:26 UTC
Labels: Bug, Duplicate
