### ISSUE TITLE
CBA functions bug

### ISSUE THREAD

**Issue by MaxPV1981** [CBATeam/CBA_A3#1570] opened 2023-02-27 19:34 UTC
- **Arma 3:** 2.10.149954 stable
- **CBA:**  v3.15.8.220912 (latest Steam)

**Description:**
Seems like CBA functions like PFH/WaitAndExecute etc are caching some params in called external functions.
Example: I have a function called OT_fnc_isDark: it just returns result of `OT_nightcoeff > 0.4`, where OT_nightcoeff dynamically changes in main cycle, depending on current lighting level. From outside CBA functions it works perfectly, but inside the call of that function returns the same value all the time - like it cached the OT_nightcoeff value.
If I retrieve the OT_nightcoeff variable inside the CBA function, the return value is correct.
Another weird behavior - the log said that it was an attempt of calling OT_fnc_isDark function, passing an object (!) as the param - while I have no such calls at all.

**Steps to reproduce:**
Run:
```
OT_nightcoeff = 0;
OT_isDark = {
	OT_nightcoeff > 0.4
};
[{
	_night = call OT_isDark;
	hint format ["Time %1, result %2",time,_night];
}, 2, []] call CBA_fnc_addPerFrameHandler;

```

**Expected behavior:**
When you change OT_nightcoeff to, say, 0.5, it is expected to see the hint returns true

**Where did the issue occur?**
Anywhere

**Comment by veteran29** [comment] 2023-02-28 01:38
The "caching" makes no sense and I'm unable to reproduce the issue, I've executed:
```sqf
OT_nightcoeff = 0;
OT_isDark = {
	OT_nightcoeff > 0.4
};
[{
	_night = call OT_isDark;
	hint format ["Time %1, result %2",time,_night];
}, 2, []] call CBA_fnc_addPerFrameHandler;
```
followed by
```sqf
OT_nightcoeff = 1;
```

and the hint updates properly.

You're using unary `call fnc` which implicitly passes `_this` and this might cause issues in your actual code as I'm pretty sure the above is not the whole thing.

**Comment by MaxPV1981** [comment] 2023-02-28 13:21
> You're using unary call fnc which implicitly passes _this
If it is `(call OT_fnc_isDark && ...` I suppose to see nothing as a passed parameter. Am I wrong?
Btw, the function parameter is 
`params [["_hardcheck",false]];`, so in standard scripts it works as expected.

> and the hint updates properly.
Hm, it has a weird behavior... Heisenbug as it is :)
Last time I played the mission, exit the session and load editor, and it worked as described above.
After your comment I tried to check it again in all configurations, starting from empty mod set, and it works in editor even in the same full mod set config.
I loaded mission, it still has the same bug (both at dedicated and local), but when I exit the mission and enter editor, it now works well.

Then I tried another function, created locally (as above), and run it on client during dedicated session - works well.
But not for standard function.
And finally I tried to explicitly put a parameter to the function call (false call OT_fnc_isDark) - and finally, it works.

So I see the difference between the functions call - for function created during the gameplay I can use call without any parameter, and it works well, but for functions, declared in CfgFunctions - it is needed to pass the parameter explicitly, if run from inside the CBA function. From the console both variants work well.

**Comment by veteran29** [comment] 2023-02-28 18:59
As I explained, unary `call` implicitly passes `_this`. 

`call fn_myFunc` isEqualTo `_this call fn_myFunc`.

This is not a scripting help forum and it does not look like it's a CBA issue so I'll be closing this issue.

**Closed by veteran29** 2023-02-28 18:59 UTC
Labels: Need More Information

**Comment by commy2** [comment] 2023-03-12 14:49
> `call fn_myFunc` ⇔ `_this call fn_myFunc`.

Unrelated to this issue, but this is not true:

```sqf
    _this = true

    private _fnc_myFunc = {
        _this = false;
    };

    _this call _fnc_myFunc

    systemChat str _this;  // true


    call _fnc_myFunc

    systemChat str _this;  // false
```

Binary `call` implicitly creates a local variable named `_this` inside the function scope, while `_this` without explicitly setting the home scope is a free variable, which means assignments leak outside the function scope.
