### ISSUE TITLE
Apex Sights Incompatible with Stock

### ISSUE THREAD

**Issue by Spooky-Mulder** [CBATeam/CBA_A3#431] opened 2016-07-13 03:00 UTC
**Arma 3 Version:** 1.62.137494 (Stable)
**CBA Version:** v2.5.0.160711

**Mods:**
- `@CBA_A3` (Other mods on machine, but disabled except for CBA to narrow issue down)

**Description:**
- Simple as that, cannot attach apex sight to non-Apex weapon. Narrowed down to CBA by testing vanilla, then enabling Steam workshop mods until issue re-presented itself. Activating CBA was the deciding factor.

**Steps to reproduce:**
- Attempt to place any Apex sight (e.x. ERCO, ) on a non-apex weapon (e.x. MX). You cannot do so by any means tested (Virtual Arsenal, or spawning sight and picking it up. Unsure about commands, but the lack of ability to do the above is significant enough, I feel.

**Where did the issue occur?**
- Occurred in self hosted multiplayer and singleplayer. Was not able to test dedicated.

**Comment by commy2** [comment] 2016-07-13 05:56
Duplicate of https://github.com/CBATeam/CBA_A3/pull/388

**Closed by commy2** 2016-07-13 05:56 UTC
