### ISSUE TITLE
Error with Russian localization of key names

### ISSUE THREAD

**Issue by YetheSamartaka** [CBATeam/CBA_A3#1246] opened 2019-10-30 10:30 UTC
After yesterday's update (Update 1.96) I'm getting this error :

11:20:50 [CBA] (settings) INFO: Reading settings from settings file.
11:20:50 [CBA] (settings) INFO: Finished reading settings from settings file.
11:20:50 [CBA] (settings) INFO: Mission Config: File [cba_settings.sqf] loaded successfully.
11:20:51 Error in expression <ring [10, 13, 9, 32] joinString "";
};

parseSimpleArray (["[", _string, "]"] jo>
11:20:51 Error position: <parseSimpleArray (["[", _string, "]"] jo>
11:20:51 Error Generic error in expression
11:20:51 File x\cba\addons\settings\fnc_parse.sqf..., line 30
11:20:51 [ACE] (common) INFO: Parsed Settings Configs [50.0 ms]
11:20:51 "SquadBarDefault: false"
11:20:51 String STR_RHS_FAC_VDV_45 not found
11:20:51 String STR_RHS_FAC_VDV_45 not found
11:20:51 [15431,237.92,0,"XEH: PreInit finished."]
11:20:51 Setting invalid pitch 0.0000 for Zeus1
11:20:59 [CBA] (settings) INFO: Mission Config: File [cba_settings.sqf] loaded successfully.
11:20:59 Error in expression <ring [10, 13, 9, 32] joinString "";
};

parseSimpleArray (["[", _string, "]"] jo>
11:20:59 Error position: <parseSimpleArray (["[", _string, "]"] jo>
11:20:59 Error Generic error in expression
11:20:59 File x\cba\addons\settings\fnc_parse.sqf..., line 30

It makes missions unstartable, ArmA III just crashes or freezes.

**Comment by commy2** [comment] 2019-10-30 10:45
Please upload the full RPT file.

**Comment by YetheSamartaka** [comment] 2019-10-30 11:23
> 
> 
> Please upload the full RPT file.

Found out, that VCOM settings in CBA_SETTINGS are causing this error, will try to isolate the problem if it isn't whole VCOM.

**Comment by YetheSamartaka** [comment] 2019-10-30 11:29
> 
> 
> Please upload the full RPT file.

Found the exact line:
force VCM_SIDEENABLED = [WEST,EAST,GUER];

If it is included it causes that error, will try to modify it, but for the moment I recommend to exclude it as comment  //force VCM_SIDEENABLED = [WEST,EAST,GUER];

**Comment by YetheSamartaka** [comment] 2019-10-30 11:43
> 
> 
> Please upload the full RPT file.


[Arma3_x64_2019-10-30_12-37-32.txt](https://github.com/CBATeam/CBA_A3/files/3788611/Arma3_x64_2019-10-30_12-37-32.txt)

**Comment by bux** [comment] 2019-10-30 11:49
needs another Lingor /s

the amount of UBCs though ...

**Comment by YetheSamartaka** [comment] 2019-10-30 12:34
Problem is restricted to the virtual zeus. Zeus with body and players are not affected.

**Comment by dedmen** [comment] 2019-10-30 14:55
`force VCM_SIDEENABLED = [WEST,EAST,GUER];`
If the string `"[WEST,EAST,GUER]"` is being passed to parseSimpleArray like that, then thats invalid, it only parses a few specific keywords (true,false,nil,null,<null>,any)
They need to be strings
`force VCM_SIDEENABLED = ["WEST","EAST","GUER"];`

**Comment by commy2** [comment] 2019-10-30 15:50
Dedmen is right. SIDE types are not supported by settings, only NUMBER, STRING and ARRAYs of these. This is because SIDE types cannot be serialized by default and I don't want to make everything ugly just to support them as they provide no functionality that cannot be achieved with supported types.

Idk whether this is an issue by VCOM or by @YetheSamartaka. It definitely is a not a problem with CBA or the update 1.96. Close?

**Comment by YetheSamartaka** [comment] 2019-10-30 19:14
After some testing, it is not related to the VCOM, problem is still there.

**Comment by commy2** [comment] 2019-10-30 19:21
RPT of a session with as few as possible mods?

**Comment by dedmen** [comment] 2019-10-30 20:11
Please attach your settings.sqf file.

**Comment by YetheSamartaka** [comment] 2019-10-31 20:11
> 
> 
> Please attach your settings.sqf file.


[cba_settings.txt](https://github.com/CBATeam/CBA_A3/files/3795645/cba_settings.txt)

**Comment by commy2** [comment] 2019-10-31 22:36
And RPT?

**Comment by YetheSamartaka** [comment] 2019-10-31 22:46
> 
> 
> And RPT?

Will provide tomorrow

**Comment by dedmen** [comment] 2019-11-02 11:39
> force ace_common_checkPBOsWhitelist = "[js

That string might cause the double quote escape issue (Which btw has been fixed on RC)

**Comment by commy2** [comment] 2019-11-04 14:25
Likely the parseSimpleArray bug from v1.96 which is now hotfixed.

**Comment by dedmen** [comment] 2019-11-13 16:41
Liquid gave me data!

```
19:31:13 "[""Web-клавиша ""Home""""]"
19:31:13 Error in expression <_formatedKeyname != "[""""""]") then {
(parseSimpleArray _formatedKeyname) selec>
19:31:13   Error position: <parseSimpleArray _formatedKeyname) selec>
19:31:13   Error Общая ошибка в выражении
19:31:13 File x\cba\addons\keybinding\XEH_preStart.sqf..., line 175

19:31:13 "[""Web-клавиша ""Поиск""""]"
19:31:13 "[""Web-клавиша ""Избранное""""]"
19:31:13 "[""Web-клавиша ""Обновить""""]"
19:31:13 "[""Web-клавиша ""Стоп""""]"
19:31:13 "[""Web-клавиша ""Вперед""""]"
19:31:13 "[""Web-клавиша ""Назад""""]"
```
I guess something with the quotes in here?
Also looks like 1.96 bug, but not fixed.

**Comment by commy2** [comment] 2019-11-13 16:57
Should've never used `parseSimpleArray`. They only ever added this, because of performance autism. Too many low skilled people are tinkering with it and it is broken every other version.

**Comment by dedmen** [comment] 2019-11-13 17:00
KK says that string is completely invalid, call compile fails on it too.

**Comment by dedmen** [comment] 2019-11-13 17:22
![Discord_2019-11-13_18-22-06](https://user-images.githubusercontent.com/3768165/68787841-907de780-0642-11ea-8d0c-dfe004cc3ada.png)

**Comment by severgun** [comment] 2019-11-13 17:51
> Despite that we didn't get any reports about that in the last 3 years that code has been there.
Seems nobody use Web keys for arma hotkeys. Or at least in russian community.
It is also simpler to rebind than create ticket.

**Comment by commy2** [comment] 2019-11-13 18:16
I have a feeling that beginning from dedmen's post today, this is a completely different thing than what OP wrote.

**Comment by severgun** [comment] 2019-11-13 18:23
yep. but fix needed here
https://github.com/CBATeam/CBA_A3/blob/6f568c08ef7a3677064e9b2dd8be477f24b19e6b/addons/keybinding/XEH_preStart.sqf#L172

**Comment by commy2** [comment] 2019-11-13 18:57
Nah. The point of those lines is to strip away the double quote marks the `keyName` command returns. If the command does not return strings with double quote marks (anymore? In Russian UI only?), then there is no point in using parseSimpleArray at all.

So the question is, what does keyName report in the English UI in 1.96? And what does it report in the Russian UI?

**Comment by commy2** [comment] 2019-11-13 18:58
Sry OP, you thread is repurposed.

**Comment by severgun** [comment] 2019-11-13 19:38
> So the question is, what does keyName report in the English UI in 1.96? And what does it report in the Russian UI?

All in Dedmen's posts above.
```keyName 0xb2```
English
```"""Web Home"""```
Russian
```"""Web-клавиша ""Home"""""```

**Comment by commy2** [comment] 2019-11-14 01:01
If I were to follow the suggested code, it gets rid of the script error, but now reports useless bull shit:
```sqf
private _keyEN = """Web Home""";
private _keyRU =  """Web-клавиша ""Home""""";

parseSimpleArray format ["[%1]", _keyEN] select 0 // "Web Home"
parseSimpleArray format ["[%1]", str _keyEN] select 0 // """""Web Home"""""
parseSimpleArray format ["[%1]", _keyRU] select 0 // "Web-клавиша " + Script error
parseSimpleArray format ["[%1]", str _keyRU] select 0 // """""Web-клавиша """"Home"""""""""
```

Now if I avoid `parseSimpleArray`, I get the correct results: 
```sqf
private _keyEN = """Web Home"""; 
private _keyRU =  """Web-клавиша ""Home"""""; 
 
private _s = str text _keyEN;
_s select [1, count _s - 2] // "Web Home"

private _s = str text _keyRU;
_s select [1, count _s - 2] // "Web-клавиша ""Home"""
```
Perfectly escaped quote marks inside strings.

The part I am angry about is, that I specifically remember having tested this, and it worked before `parseSimpleArray` was changed (recently or months ago, changes happen frequently it seems).

**Comment by commy2** [comment] 2019-11-14 01:13
>Seems nobody use Web keys for arma hotkeys. Or at least in russian community.
It is also simpler to rebind than create ticket.

All key names are converted and cached at game start (it is a preStart script after all). It does not matter what key is bound to what.

Anyway, thanks for the help everyone. Fix on weekend.

**Comment by commy2** [comment] 2019-11-14 21:59
Changed to RUSSKIE localization:
```sqf
0xB2 call CBA_fnc_localizeKey // "Web-клавиша ""Home"""
```
No errors.

**Comment by Dystopian** [comment] 2019-11-15 11:02
meanwhile in [Development Branch Changelog](https://forums.bohemia.net/forums/topic/140837-development-branch-changelog/?do=findComment&comment=3386320)

> Fixed: Un-escaping double quotes in parseSimpleArray

**Comment by commy2** [comment] 2019-11-15 14:26
Yeah, but at this point, I am just tired of their shit. They will likely break it again.

**Closed** 2019-11-15 15:11 UTC
Labels: Bug

**Comment by severgun** [comment] 2019-11-15 17:42
> All key names are converted and cached at game start (it is a preStart script after all). It does not matter what key is bound to what.

As I understand this strings are used in keybinding menu. So because no one use Web keys no one notice corrupted strings.

> 0xB2 call CBA_fnc_localizeKey // "Web-клавиша ""Home"""

Double double quotes inside are not correct actually. But better than error I think.

**Comment by commy2** [comment] 2019-11-15 21:54
>As I understand this strings are used in keybinding menu. So because no one use Web keys no one notice corrupted strings.

All keynames are cached on game start. The current code results in a script error. Script errors on game start have a high chance to crash the application, due to a bug with the error popup message. This is not a trivial bug.

>Double double quotes inside are not correct actually. But better than error I think.

But those are not double quotes when displayed on controls. They are escaped quote marks. Just execute:
```sqf
hintSilent "Web-клавиша ""Home"""
```
It will look exactly as intended.

**Comment by dedmen** [comment] 2019-11-18 14:29
> Fixed: Un-escaping double quotes in parseSimpleArray
not related.
