### ISSUE TITLE
Cant join Server - not signed

### ISSUE THREAD

**Issue by yfstein** [CBATeam/CBA_A3#1149] opened 2019-05-24 12:14 UTC
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `v3.11.2.190515` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
- If i try to join to my server its telling me, that the files are not signed (key is not accepted). We checked the installation with 5 guys and all trying to get it working (All have experience in mod-servers) but nobody can get it run. We found 50 bisign on 25pbos and in GitHub the Server keys not included? I think their got a bug on bump to actual version, cauz before two weeks i got it running, but not the newest version. Can u validate?

**Steps to reproduce:**
- Downloaded CBA_A3 from Armaholic, copied the keys to the keyfolder, deleted the keyfolder in the modfolder, copy modfolder to local client and server, edit your start parameter to -mods=@CBA_A3; and try to join the server after startup.

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- isnt needed - no important informations in there.

**Comment by bux** [comment] 2019-05-24 12:19
Yeah, I can confirm that you and the 5 experienced guys are doing something wrong.

**Comment by commy2** [comment] 2019-05-24 12:21
>isnt needed - no important informations in there.

Ok. Tempted to close this issue just for this tbh.

**Comment by commy2** [comment] 2019-05-24 12:22
Needs RPT.

**Comment by yfstein** [comment] 2019-05-24 13:39
[arma3server_2019-05-24_15-33-58.rpt.log](https://github.com/CBATeam/CBA_A3/files/3217105/arma3server_2019-05-24_15-33-58.rpt.log)

**Comment by commy2** [comment] 2019-05-24 17:53
Needs client RPT.

**Comment by yfstein** [comment] 2019-05-24 21:44
https://pastebin.com/MNe877cy

**Comment by commy2** [comment] 2019-05-25 03:59
That RPT does not help, because nothing is recorded due to `-nologs`. Needs an RPT with logging enabled.

**Comment by yfstein** [comment] 2019-05-25 09:24
[Arma3_x64_2019-05-25_11-22-24.rpt.log](https://github.com/CBATeam/CBA_A3/files/3219260/Arma3_x64_2019-05-25_11-22-24.rpt.log)

**Comment by commy2** [comment] 2019-05-25 11:33
Close Steam via Task Manager or command promp, or restart the client machine. Reopen Steam. Delete `Arma 3/@CBA_A3/Keys` folder and let Steam redownload.

**Comment by joshhroberts** [comment] 2019-05-26 15:12
> Close Steam via Task Manager or command promp, or restart the client machine. Reopen Steam. Delete `Arma 3/@CBA_A3/Keys` folder and let Steam redownload.

I need key, I follow steps, but I do not have the key

**Comment by commy2** [comment] 2019-05-26 23:24
The server key is in the @CBA_A3/keys folder, as always.
cba_3.11.2.190515.bikey

**Comment by Ateir** [comment] 2019-07-07 17:36
There is definitely something wrong with the files uploaded to Armaholic, just encountered this issue myself. There is a mismatch between version and key. Also the files give you two keys, which makes me think something has happened here.

Using the files from github, seems to have done the trick for now.

**Comment by commy2** [comment] 2019-07-07 17:55
We don't manage the upload to Armaholic.

**Comment by dedmen** [comment] 2019-07-09 08:25
Armaholic has 11.0 and 11.2 keys, arma should just ignore the missmatching 11.0 keys and use the correct ones.
Don't download broken armaholic garbage. 
Also OP is running Exile which we know loves to mess with and break everything they can get their hands on.
Close?

**Closed** 2019-07-09 15:20 UTC
Labels: Need More Information
