### ISSUE TITLE
CBA interfering with weapon Suppressors

### ISSUE THREAD

**Issue by DutchVidya** [CBATeam/CBA_A3#521] opened 2016-10-05 14:27 UTC
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0.160928
` (stable)

**Mods:**
- `@CBA_A3`
- `@ACE`

**Description:**
When game is launched with CBA, any weapon capable of taking a vanilla suppressor either does not have one, or is given access to every suppressor from the vanilla game. As an example, the MX rifle is given access to _every_ suppressor from the vanilla game. This is affecting even weapons from other mods that inherit these attachments. As an example, this is the [MX rifle.](http://puu.sh/ryzFX/9c6e84d38c.png) 

I have confirmed it is CBA that is responsible, as at the time of this testing, CBA is the _only mod running_.

What's odd, is that it has not happened to every person' game. This issue has persisted for me since the launch of APEX, but I know many people who run the same modset who do not have this issue. Some users, like myself are seeing broken suppressors on every weapon, others are only seeing it on the Katiba and MX family of rifles. One reported his M320 GL sidearm from [RHS was being given a suppressor](http://images.akamai.steamusercontent.com/ugc/250338860234861056/FC22EA1562A9802051763A499665AAFC5542C358/).

Further, when the game is launched with only ACE and CBA, it stops any pistol suppressors from appearing at all.

Something is interfering with weapon muzzle devices, and CBA seems to be the common cause.

**Steps to reproduce:**
Launch CBA alongside the vanilla game

**Where did the issue occur?**
This issue occurs in every area of the game.

**RPT log file:**
[My rpt file at the time of the most recent test.](http://puu.sh/ryzQw/756de5a14e.rpt)

**Comment by robalo** [comment] 2016-10-05 15:47
MX rifle was given the 7.62 JointRails muzzle plus it can use the 6.5mm vanilla suppressors. So it's intended behavior there. I made more sense based on real life to use a 7.62 compatible muzzle device adapter instead of a dedicated 6.5mm one. Initially I didn't even add JR support for these weapons because I wanted to avoid these kind of "issues" but then it has been requested.

For any issues with RHS, ACE or any other mod, please report to them directly so they can be addressed in their implementation of JR. If a mod does not provide JR (joint rails) support then there is nothing we can  do, it will simply be incompatible with CBA.

The ACE pistol muzzle issue has already been patched as far as I know in their source so it will be fixed next ACE release.

**Closed** 2016-10-22 17:09 UTC
